### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by DionJoel** [oubaydos/flipsnack-to-pdf#2] opened 2021-12-11 14:08 UTC
Every time I execute it in my terminal it crashes or do I get something wrong ?

**Comment by DionJoel** [comment] 2021-12-11 14:16
Terminal output:

Traceback (most recent call last):
  File "index.py", line 1, in <module>
    from logs_generator import generate_logs
  File "/home/dion-hannah/Musik/flipsnack-to-pdf-main/logs_generator.py", line 3, in <module>
    import validators
ImportError: No module named validators

**Comment by oubaydos** [comment] 2021-12-11 14:40
hello mr DionJoel, thanks for opening this issue,
before using my script, you should install the requirements mentionned in the [ReadMe](https://github.com/oubaydos/flipsnack-to-pdf#requirements) file.

After that if you still have an issue please reply, otherwise you can close the issue

**Comment by DionJoel** [comment] 2021-12-11 14:51
Everything is installed (requirements already satisfied).

**Comment by oubaydos** [comment] 2021-12-11 15:24
Hmm this is weird, do you still have the same problem ? can you regenerate it ? if that is the case make sure that the same python version you are using to run the index.py has the same pip where you installed the packages! 

You can use this command to install packages :  ```python -m pip install moduleName```
And then run the index file using this command ```python index.py```

And if it doesnt work, please reply with the errors
Thanks.
Obaydah

**Comment by DionJoel** [comment] 2021-12-12 21:35
I needed to specify the Python Version to **python3** and now I get an Stacktrace Error

![Pasted image 20211212223402](https://user-images.githubusercontent.com/68860957/145730436-4867a298-7b4f-4169-bef4-599d3ee3c08b.png)

**Comment by oubaydos** [comment] 2021-12-12 23:37
yes so the problem is that i specified brave browser as my chrome driver, i will be updating the script in the next 2-3 days to support all the chromium based drivers. Thanks for opening this issue, you may close it now
Thanks
Obaydah

**Closed** 2021-12-13 17:17 UTC
Labels: bug
